logging:
  file:
    name: mailer.log
  pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    .: info
    org.springframework.web: ERROR